[2022-05-16 09:42:56,523] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: test4.schedule_bgg_crawler 2022-05-16T09:35:00+00:00 [queued]>
[2022-05-16 09:42:56,529] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: test4.schedule_bgg_crawler 2022-05-16T09:35:00+00:00 [queued]>
[2022-05-16 09:42:56,529] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2022-05-16 09:42:56,529] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2022-05-16 09:42:56,529] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2022-05-16 09:42:56,535] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): schedule_bgg_crawler> on 2022-05-16T09:35:00+00:00
[2022-05-16 09:42:56,536] {standard_task_runner.py:52} INFO - Started process 500 to run task
[2022-05-16 09:42:56,538] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'test4', 'schedule_bgg_crawler', '2022-05-16T09:35:00+00:00', '--job-id', '38', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/test/test.py', '--cfg-path', '/tmp/tmpsh6a8vk9', '--error-file', '/tmp/tmpcmryj1mk']
[2022-05-16 09:42:56,538] {standard_task_runner.py:77} INFO - Job 38: Subtask schedule_bgg_crawler
[2022-05-16 09:42:56,565] {logging_mixin.py:104} INFO - Running <TaskInstance: test4.schedule_bgg_crawler 2022-05-16T09:35:00+00:00 [running]> on host 806ad1237b61
[2022-05-16 09:42:56,630] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test4
AIRFLOW_CTX_TASK_ID=schedule_bgg_crawler
AIRFLOW_CTX_EXECUTION_DATE=2022-05-16T09:35:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-16T09:35:00+00:00
[2022-05-16 09:42:56,630] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-05-16 09:42:56,631] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'cd /opt/***/dags && scrapy crawl thongbao && echo "xong t1"']
[2022-05-16 09:42:56,635] {subprocess.py:75} INFO - Output:
[2022-05-16 09:42:56,636] {subprocess.py:79} INFO - bash: scrapy: command not found
[2022-05-16 09:42:56,637] {subprocess.py:83} INFO - Command exited with return code 127
[2022-05-16 09:42:56,643] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-05-16 09:42:56,644] {taskinstance.py:1544} INFO - Marking task as FAILED. dag_id=test4, task_id=schedule_bgg_crawler, execution_date=20220516T093500, start_date=20220516T094256, end_date=20220516T094256
[2022-05-16 09:42:56,669] {local_task_job.py:151} INFO - Task exited with return code 1
